/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Fri, 26 Apr 2024 07:24:04 GMT
///
export { request } from '../sdk-interface';
